### ISSUE TITLE
TypeError: pushFile() takes at least 5 arguments (3 given)

### ISSUE THREAD

**Issue by Artanicus** [Azelphur/pyPushBullet#18]
The example:
./pushbullet_cmd.py YOUR_API_KEY_HERE file udeCmddJpl test.jpg

Doesn't seem to work;
Traceback (most recent call last):
  File "./pushbullet_cmd.py", line 149, in <module>
    args.func(args)
  File "./pushbullet_cmd.py", line 95, in pushFile
    file = p.pushFile(args.device, open(args.file, 'rb'))
TypeError: pushFile() takes at least 5 arguments (3 given)

**Comment by Azelphur** [comment]
Thanks, fixed :)
