### ISSUE TITLE
getdevices assumes manufacturer is set

### ISSUE THREAD

**Issue by Artanicus** [Azelphur/pyPushBullet#19]
Sample output;

<devid> motorola Nexus 6
<devid> LGE Nexus 5
<devid> htc Nexus 9
<devid> Google Chrome
<devid> asus Nexus 7
Traceback (most recent call last):
  File "./pushbullet_cmd.py", line 149, in <module>
    args.func(args)
  File "./pushbullet_cmd.py", line 38, in getDevices
    device["manufacturer"],
KeyError: 'manufacturer'

Manufacturer is not a mandatory field for custom API clients and shouldn't be assumed to be set.

**Comment by Azelphur** [comment]
Thanks, fixed :)
