### ISSUE TITLE
Allow use from pip

### ISSUE THREAD

**Issue by voltagex** [Azelphur/pyPushBullet#23]
Any chance of adding a setup.py and moving the module into a pyPushBullet folder? That way the module can be downloaded with pip.

**Comment by Azelphur** [comment]
Amusingly making a pip package is one of those things I haven't learned to do yet, I imagine it's easy I just haven't dug into it yet. Patches welcome on the setup.py stuff, or I will do it when I have time :)

**Comment by voltagex** [comment]
I have a branch that fixes this. Ping me if I don't finish it by next week

**Comment by voltagex** [comment]
#24 created
