### ISSUE TITLE
Pip install cannot unpack; cannot detect archive format

### ISSUE THREAD

**Issue by icebal** [Azelphur/pyPushBullet#25]
Cannot unpack file c:\temp\pip-honfwr-unpack\pyPushBullet (downloaded from c:\appdata\local\temp\pip-ebcta8-build, content-type: text/html; charset=utf-8); cannot detect archive format  Cannot determine archive format of c:\appdata\local\temp\pip-ebcta8-build
this is the error given with either python 2.7 or python3. i edited out the user info. this happens when trying to run "pip install  https://github.com/Azelphur/pyPushBullet" on linux or windows, admin or not. pip is updated to the newest version.

**Comment by Azelphur** [comment]
Seems like you're trying to run the wrong command, the correct command is

`pip install git+https://github.com/Azelphur/pyPushBullet.git`

**Comment by g-o-o-g-l-e** [comment]
PS C:\Users\-----\PycharmProjects\1stPrj> pip install https://github.com/google/mediapipe
Collecting https://github.com/google/mediapipe
  Downloading https://github.com/google/mediapipe
     - 374.0 kB 24.3 MB/s 0:00:00
  ERROR: Cannot unpack file C:\Users\ethan\AppData\Local\Temp\pip-unpack-_i00o3zp\mediapipe (downloaded from C:\Users\ethan\AppData\Local\Temp\pip-req-build-uezph6gc, c
ontent-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\ethan\AppData\Local\Temp\pip-req-build-uezph6gc

**Comment by g-o-o-g-l-e** [comment]
i can't install mediapipe in anyway
