### ISSUE TITLE
ImportError: cannot import name PushBullet

### ISSUE THREAD

**Issue by EnricoSx** [Azelphur/pyPushBullet#31]
hello i try to use pyPushBullet on Raspian Jessie.

my script allarme.py
.....
print ("Inizializzazione PushBullet...")
from pushbullet.pushbullet import PushBullet
apiKey = "vagferxxxxxxxxxxxxxxxxxxxxxxxx"
p = PushBullet(apiKey)
p.pushNote(devices[0]["raspberry"], 'Allarme', 'Avvio allarme in corso...')
......
result:

Traceback (most recent call last):
  File "allarme.py", line 4, in <module>
    from pushbullet.pushbullet import PushBullet
ImportError: cannot import name PushBullet

can you help me?

**Comment by zoolii** [comment]
I have some issue

Traceback (most recent call last):
  File "./pushbullet_cmd.py", line 19, in <module>
    from pushbullet import PushBullet
ImportError: cannot import name PushBullet

**Comment by Azelphur** [comment]
You both seem to have different issues, however I believe both issues are fixed now.
