### ISSUE TITLE
Looking for a way to receive pushes

### ISSUE THREAD

**Issue by kencodes** [Azelphur/pyPushBullet#32]
I have an automation script that I want to control with a Pushbullet interface.  It already sends out status pushes to my channel just fine, but I don't see a way to use your code to remotely control my script through pushbullet.

Is this something you already support or plan to support?
-Ken

**Comment by Azelphur** [comment]
If I understand you correctly, you want your script to register as a device and listen for pushes sent to it? you can use the addDevice and realtime functions for this
