### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by J-Lich** [Azelphur/pyPushBullet#33]
I know there has been a previous issue in regards to ImportErrors but I was unable to solve my issue. (I am also new here so let me know If I am doing anything wrong.)

I am using the pyPushBullet module on OSX installed via pip and it works flawlessly, however, when I transferred the code to my ubuntu 14.04 computer I keep getting import errors, even on the simplest of tests;

```
#!/usr/bin/python3.4
from pushbullet import PushBullet

pb = PushBullet('my_access_token')
success, push = pb.push_note("Testing title", "Hello world!")

```

RETURNS:

> Traceback (most recent call last):
>   File "./test.py", line 2, in <module>
>     from pushbullet import PushBullet
> ImportError: cannot import name 'PushBullet'

I think it may be some sort of installation error, but I have no idea. Any help would be fantastic.

Cheers,
James

**Comment by adarshsanjeev** [comment]
I believe it is 
`from pushbullet.pushbullet import PushBullet`
as given in the README
