### ISSUE TITLE
Cannot install logpy on Ubuntu; python3.6.9

### ISSUE THREAD

**Issue by kelvinmakau** [Azelphur/pyPushBullet#54]
pip3 install logpy
Collecting logpy
  Using cached https://files.pythonhosted.org/packages/b7/58/53ce8f101c036dd848f86fe6ebedcd849aa4802e1cfc5f613a31f7e93852/LogPy-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_jzw89c0/logpy/setup.py", line 6, in <module>
        long_description = open('README.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

**Comment by Azelphur** [comment]
This project makes no use of logpy and it's not a dependency, not sure why you filed the bug here.
From the looks of the traceback it seems like this is an issue in the logpy setup.py file, so you should file a bug against logpy.
