### ISSUE TITLE
cannot install module mhs5200 in python

### ISSUE THREAD

**Issue by jayaminimadumali** [Azelphur/pyPushBullet#55]
I used  pip install https://github.com/jed-frey/python_mhs5200.git but it is not working 
gives me this error. I also downloaded git still not working

 ERROR: Cannot unpack file C:\Users\jayam\AppData\Local\Temp\pip-unpack-s_569cqf\python_mhs5200.git (downloaded from C:\Users\jayam\AppData\Local\Temp\pip-req-build-ym52tazk, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\jayam\AppData\Local\Temp\pip-req-build-ym52tazk

**Comment by Azelphur** [comment]
Not sure why you've opened an issue against pyPushBullet for this. pyPushBullet is nothing to do with mhs5200. The problem you're having is that the URL you're providing is incorrect, refer to the mhs5200 installation instructions for a correct example.
