### ISSUE TITLE
Cannot add mediapipe on pycharm

### ISSUE THREAD

**Issue by g-o-o-g-l-e** [Azelphur/pyPushBullet#58]

**Comment by g-o-o-g-l-e** [comment]
I cannot install mediapipe

**Comment by g-o-o-g-l-e** [comment]
I asked in #57 
but no one ans me

**Comment by g-o-o-g-l-e** [comment]
This the errors
ERROR: Could not find a version that satisfies the requirement pycharm (from versions: none)
ERROR: No matching distribution found for pycharm

**Comment by g-o-o-g-l-e** [comment]
#57 need my help

**Comment by g-o-o-g-l-e** [comment]
I have been thinking for 3 months about it

**Comment by g-o-o-g-l-e** [comment]
please help me

**Comment by g-o-o-g-l-e** [comment]
please help me I am using 3.12 on pycharm and 64-bit but I can't use the pip way to install mediapipe

**Comment by g-o-o-g-l-e** [comment]
stat:awaiting response

**Comment by Azelphur** [comment]
Wow.

I am not a support platform. Expecting a response within seconds is completely unreasonable. Spamming issue creation, comments, and spam opening/closing tickets on this repository or any repository is completely unacceptable. I am closing all your issues and will not provide you with any support.
